# Generated by Django 4.0.1 on 2022-01-12 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(max_length=600)),
                ('client_code', models.CharField(max_length=200, unique=True)),
                ('address', models.CharField(blank=True, max_length=600, null=True)),
                ('national_id', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/client/%y/%m')),
                ('phone', models.CharField(max_length=200, unique=True)),
                ('status', models.BooleanField(blank=True, default=True, null=True)),
                ('slug', models.SlugField(blank=True, max_length=128, null=True, unique=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'lawyer_client',
            },
        ),
        migrations.CreateModel(
            name='IMEI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imei_number', models.PositiveIntegerField()),
                ('extraction_date', models.DateField()),
                ('imei_check', models.CharField(choices=[('OK', 'OK'), ('Stolen', 'Stolen'), ('NO-INFO', 'NO IN DB')], max_length=200)),
                ('status', models.BooleanField(default=False)),
                ('slug', models.SlugField(blank=True, max_length=128, null=True, unique=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='client_imei', to='phone.client')),
            ],
            options={
                'verbose_name': 'imei_user',
            },
        ),
    ]
