# Generated by Django 4.0.1 on 2022-01-12 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0002_alter_imei_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imei',
            name='extraction_date',
        ),
        migrations.AddField(
            model_name='client',
            name='client_type',
            field=models.CharField(choices=[('تاجر', 'تاجر'), ('مالك اول', 'مالك اول'), ('مالك ثاني', 'مالك ثاني')], default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imei',
            name='buy_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='imei',
            name='sell_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='imei',
            name='imei_check',
            field=models.CharField(choices=[('جيد', 'جيد'), ('مسروق', 'مسروق'), ('غير مضاف في ثاعدة البيانات', 'غير مضاف في ثاعدة البيانات')], max_length=200),
        ),
    ]
