# Generated by Django 4.0.1 on 2022-01-12 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0003_remove_imei_extraction_date_client_client_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imei',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/IMEI/%y/%m'),
        ),
    ]
